
# .codecov.yml
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 70%

ignore:
  - "tests/"
  - "examples/"
  - "docs/"
  - "scripts/"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
