# docker-compose.yml
version: '3.8'

services:
  fantasy-novel-mcp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LLM__API_BASE=${LLM_API_BASE:-http://host.docker.internal:8000/v1}
      - LLM__API_KEY=${LLM_API_KEY:-your-api-key}
      - LLM__MODEL_NAME=${LLM_MODEL_NAME:-qwen2.5-72b-instruct}
      - DATABASE__URL=sqlite:///app/data/fantasy_novel.db
      - REDIS__HOST=redis
      - MCP__DEBUG=false
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - fantasy-novel-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - fantasy-novel-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - fantasy-novel-mcp
    restart: unless-stopped
    networks:
      - fantasy-novel-net

volumes:
  redis_data:

networks:
  fantasy-novel-net:
    driver: bridge

