
# config/prompts/character.yaml
# 角色创建提示词模板

basic_info: |
  为{{ genre }}小说创建一个{{ character_type }}角色：

  特殊要求：{{ requirements }}

  请生成角色的基本信息：
  1. 姓名（符合世界观设定）
  2. 性别和年龄
  3. 在故事中的作用和重要性
  4. 角色弧线概述
  5. 与其他角色的关系

  要求：
  - 姓名要有含义且好记
  - 符合{{ character_type }}的典型特征
  - 为后续发展留下空间

appearance: |
  为角色{{ name }}设计外貌特征：

  世界设定：{{ world_setting }}

  请描述：
  1. 基本体貌特征（性别、年龄、身高、体型）
  2. 五官特点（面容、眼睛、发型）
  3. 肤色和体质特征
  4. 独特标识（疤痕、胎记、特殊之处）
  5. 穿衣风格和喜好
  6. 常用配饰和装备
  7. 整体气质和第一印象

  要求：
  - 外貌要与角色性格相符
  - 体现角色的身份地位
  - 便于读者记忆和识别

personality: |
  为角色{{ name }}（{{ character_type }}）设计性格特征：

  请详细描述：
  1. 核心性格特质（3-5个主要特点）
  2. 优点和长处
  3. 缺点和弱点
  4. 恐惧和忌讳
  5. 欲望和追求
  6. 行为习惯和口头禅
  7. 说话方式和语言特色
  8. 道德观念和价值取向
  9. 情绪表达方式
  10. 人际交往特点

  要求：
  - 性格要有层次感
  - 优缺点要平衡
  - 符合{{ character_type }}的角色定位
  - 为角色成长提供空间

background: |
  为角色{{ name }}创建详细背景：

  世界设定：{{ world_setting }}

  请包含：
  1. 出生地和成长环境
  2. 家庭情况和主要亲属
  3. 童年和青少年经历
  4. 教育背景和师承
  5. 重要的人生事件
  6. 人际关系网络
  7. 社会地位和财富状况
  8. 个人秘密和隐私
  9. 未实现的愿望
  10. 人生目标和动机

  要求：
  - 背景要与世界观一致
  - 重要事件要有前因后果
  - 为角色行为提供合理动机

abilities: |
  为角色{{ name }}设计能力体系：

  小说类型：{{ genre }}
  世界设定：{{ world_setting }}

  请设计：
  1. 当前实力等级
  2. 修炼功法或特殊能力
  3. 战斗技能和招式
  4. 非战斗技能（学识、手艺等）
  5. 天赋特质和潜力
  6. 拥有的法宝/装备
  7. 实力成长路径
  8. 能力的限制和弱点

  要求：
  - 符合世界的力量体系
  - 实力与角色设定匹配
  - 留有成长空间
