

# config/prompts/plot.yaml
# 情节规划提示词模板

basic_story: |
  为小说《{{ title }}》创建基础故事信息：

  类型：{{ genre }}
  主题：{{ theme }}
  角色：{{ characters }}
  世界设定：{{ world_setting }}

  请生成：
  1. 故事前提和核心概念
  2. 主要矛盾和冲突
  3. 故事基调和风格
  4. 主角和反派的设定
  5. 核心赌注（stakes）
  6. 三幕结构概述：
     - 第一幕：开端和设定
     - 第二幕：发展和冲突
     - 第三幕：高潮和结局
  7. 主要主题元素
  8. 象征和隐喻

  要求：
  - 故事要有吸引力
  - 冲突要有张力
  - 主题要有深度

story_outline: |
  为{{ genre }}小说《{{ title }}》创建详细大纲：

  章节数量：{{ chapter_count }}
  主要角色：{{ characters }}
  世界背景：{{ world_setting }}

  请创建包含以下要素的完整大纲：

  1. 故事概述
  2. 主要角色关系图
  3. 核心冲突设定
  4. 章节分布规划：
     - 每章主要事件
     - 情节推进要点
     - 角色发展节点
     - 紧张程度变化
  5. 重要情节点：
     - 起始事件
     - 转折点
     - 高潮场面
     - 结局设定
  6. 子情节线索
  7. 主题发展脉络

  要求：
  - 情节要有逻辑性
  - 节奏要有起伏
  - 角色要有成长

conflict_generation: |
  基于以下信息生成故事冲突：

  主角：{{ protagonist }}
  反派：{{ antagonist }}
  故事背景：{{ setting }}
  主题：{{ theme }}

  请生成以下类型的冲突：

  1. 核心冲突（主角vs反派）：
     - 冲突原因和根源
     - 双方的立场和目标
     - 冲突的发展过程
     - 可能的解决方式

  2. 内心冲突（主角内在矛盾）：
     - 价值观冲突
     - 道德选择困境
     - 恐惧与欲望对立

  3. 环境冲突（外在阻碍）：
     - 自然环境挑战
     - 社会制度限制
     - 时间压力等

  4. 人际冲突（角色间摩擦）：
     - 利益冲突
     - 理念分歧
     - 误解和偏见

  要求每个冲突都要有具体的表现形式和发展可能。
