
# config/prompts/tools.yaml
# 工具类提示词模板

character_names: |
  为{{ style }}风格的{{ gender }}角色生成{{ count }}个姓名：

  角色特质：{{ traits }}
  避免使用：{{ avoid_list }}

  要求：
  1. 姓名要有文化特色
  2. 音韵要优美易记
  3. 含义要积极正面
  4. 适合角色的地位身份
  5. 避免与现有角色重名

  请为每个姓名提供：
  - 姓名本身
  - 含义解释
  - 适用的角色类型

place_names: |
  生成{{ count }}个{{ place_type }}的地名：

  文化风格：{{ style }}
  地理特征：{{ features }}

  要求：
  1. 符合地理特征
  2. 体现文化背景
  3. 朗朗上口好记
  4. 有历史感和深度
  5. 适合故事氛围

  请说明每个地名的：
  - 地名含义
  - 地理特色
  - 历史背景

technique_names: |
  生成{{ count }}个{{ type }}技能名称：

  威力等级：{{ level }}
  元素属性：{{ element }}

  要求：
  1. 名称要威风霸气
  2. 体现技能特色
  3. 符合等级定位
  4. 有文化内涵
  5. 便于记忆传播

  每个技能名称包含：
  - 技能名称
  - 威力描述
  - 使用条件

artifact_names: |
  生成{{ count }}个{{ type }}法宝名称：

  稀有程度：{{ rarity }}
  制作材料：{{ material }}

  要求：
  1. 名称要显示珍贵
  2. 体现功能特色
  3. 有神秘色彩
  4. 符合材料特性
  5. 朗朗上口

  每个法宝包含：
  - 法宝名称
  - 主要功能
  - 外观特征

organization_names: |
  生成{{ count }}个{{ type }}组织名称：

  阵营倾向：{{ alignment }}
  专长领域：{{ specialty }}

  要求：
  1. 体现组织性质
  2. 显示实力地位
  3. 有威严感
  4. 朗朗上口
  5. 富有特色

  每个组织包含：
  - 组织名称
  - 组织理念
  - 影响范围

timeline_analysis: |
  分析以下时间线的一致性：

  事件列表：{{ events }}
  时间跨度：{{ timespan }}

  请检查：
  1. 时间顺序的逻辑性
  2. 事件间的因果关系
  3. 角色行程的合理性
  4. 季节时间的一致性
  5. 重大事件的影响持续时间

  指出可能的问题并提供修改建议。

consistency_check: |
  检查以下元素的一致性：

  检查对象：{{ elements }}
  参考标准：{{ standards }}

  请从以下角度分析：
  1. 内在逻辑一致性
  2. 与已建立设定的符合度
  3. 角色行为的合理性
  4. 情节发展的连贯性
  5. 世界观的统一性

  为每个问题提供具体的修改建议。
