# config/prompts/worldbuilding.yaml
# 世界观构建提示词模板 - 补充完整版

basic_world: |
  请为一部{{ genre }}小说创建基础世界设定，主题为{{ theme }}，规模为{{ scale }}。

  请包含以下要素并以JSON格式返回：
  - name: 世界名称
  - type: 世界类型（{{ scale }}）
  - time_period: 时代背景
  - technology_level: 科技水平
  - magic_prevalence: 魔法普及程度
  - political_system: 政治体系
  - major_races: 主要种族列表
  - major_kingdoms: 主要王国/势力（包含name和description）
  - natural_features: 自然特征列表
  - unique_elements: 独特元素列表
  - history_timeline: 历史时间线（包含period和event）
  - culture_notes: 文化特色描述
  - economy_system: 经济体系
  - languages: 语言系统列表

  要求：
  1. 符合{{ genre }}小说的常见设定
  2. 体现{{ theme }}主题特色
  3. 世界观要有内在逻辑性
  4. 为后续情节发展留下空间

detailed_politics: |
  基于已有的世界设定{{ world_name }}（{{ world_type }}），请详细描述其政治体系。

  现有信息：{{ existing_info }}

  请重点阐述：
  1. 政治结构和权力分配
  2. 主要政治势力及其关系
  3. 法律制度和司法体系
  4. 外交政策和国际关系
  5. 政治冲突和潜在问题

  要求描述详细且符合{{ genre }}小说的世界观。

detailed_economy: |
  基于世界设定{{ world_name }}，请详细描述其经济体系。

  现有信息：{{ existing_info }}

  请包含：
  1. 货币制度和金融体系
  2. 主要产业和贸易
  3. 资源分布和开发
  4. 商业组织和商路
  5. 经济政策和管理制度

  要求符合世界的科技水平和魔法设定。

detailed_culture: |
  基于世界设定{{ world_name }}，请详细描述其文化体系。

  现有信息：{{ existing_info }}

  请详细阐述：
  1. 宗教信仰和神话体系
  2. 社会习俗和传统节日
  3. 艺术形式和文学传统
  4. 教育体系和知识传承
  5. 社会阶层和价值观念
  6. 婚姻制度和家庭结构
  7. 礼仪规范和社交准则
  8. 各种族的文化差异

  要求：
  - 文化要与世界观保持一致
  - 体现不同种族的特色
  - 为角色行为提供文化背景

detailed_history: |
  基于世界设定{{ world_name }}，请详细描述其历史发展。

  现有信息：{{ existing_info }}

  请创建详细的历史时间线，包含：
  1. 远古时代：世界起源和创世神话
  2. 上古时期：各种族的兴起和分化
  3. 古代时期：第一批文明和王国建立
  4. 中古时期：重大战争和朝代更替
  5. 近古时期：文化发展和技术进步
  6. 现代背景：当前时代的重要事件

  每个时期请说明：
  - 主要历史事件和转折点
  - 重要人物和英雄传说
  - 技术和文化发展
  - 对当前世界的影响

  要求历史要有连贯性和因果关系。

world_conflicts: |
  基于世界设定，请生成主要的世界冲突和矛盾：

  王国势力：{{ kingdoms }}
  主要种族：{{ races }}
  政治体系：{{ political_system }}

  请生成：
  1. 政治冲突（王国间、内部斗争）
  2. 种族矛盾（历史恩怨、利益冲突）
  3. 资源争夺（领土、稀有资源）
  4. 宗教/文化冲突
  5. 外部威胁

  每个冲突请说明原因、现状和可能发展。

world_mysteries: |
  为世界{{ world_name }}创造神秘元素和未解之谜：

  独特元素：{{ unique_elements }}
  历史背景：{{ history }}

  请创造：
  1. 古老的遗迹和秘密
  2. 失传的知识和技术
  3. 神秘的现象和传说
  4. 隐藏的势力和组织
  5. 预言和命运相关的谜团

  要求：
  - 与世界设定保持一致
  - 为故事情节提供发展空间
  - 增加世界的神秘感和深度

magic_system: |
  为{{ world_type }}世界创建魔法/修炼体系，复杂程度：{{ complexity }}

  请设计包含以下元素的体系：
  1. 体系名称和基本原理
  2. 力量来源（灵气、魔力、信仰等）
  3. 修炼/使用方法
  4. 实力等级划分（至少7个等级）
  5. 能力分类（元素、特殊能力等）
  6. 限制条件和代价
  7. 相关器具和辅助物品
  8. 修炼组织和传承

  要求：
  - 体系要有内在逻辑
  - 等级差距明显但合理
  - 适合{{ world_type }}的世界观

geography: |
  为世界{{ world_name }}（规模：{{ world_scale }}）设计地理环境：

  请创建：
  1. 主要大陆和地形分布
  2. 重要城市和地标
  3. 自然奇观和特殊地貌
  4. 气候带和环境特征
  5. 资源分布和矿产
  6. 危险区域和禁地
  7. 交通路线和贸易通道
  8. 各区域的文化特色

  要求：
  - 地理要素相互关联
  - 符合自然规律
  - 支撑故事发展需要
